# Generated by Django 4.0.4 on 2022-06-03 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_caategory_post_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Caategory',
            new_name='Category',
        ),
    ]
