# Generated by Django 4.0.4 on 2022-06-14 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_body_comment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='simble_body',
            new_name='snippet',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_tag',
        ),
    ]
